version: '3.9'

services:
    postgres:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data:z
        environment:
            - POSTGRES_NAME=sparrow
            - POSTGRES_USER=sparrow
            - POSTGRES_PASSWORD=sparrow
        ports:
            - '5432:5432'
    redis:
        image: redis
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - '6379:6379'
